### ISSUE TITLE
Scroll Action

### ISSUE THREAD

**Issue by anandb5** [garthenweb/react-native-e2etest#3]
I'm writing an automation code using Appium fro react native application. Firstly can able to perform click action. Further, I need to find the element and click which is maybe on next screen, for this, I need to perform click action till I find that element.
Which method do I need to use, Do I need to set accessibility label for screen also?

**Comment by dimplechauhan21** [comment]
I'am facing same issue. I'm able to launch the app but to go to particular element within same screen the action that needs to be performed is scrolling down the page and identify the element. 
for which i'm not able to find solution

**Comment by AvinashPratap** [comment]
i am also writing a script and i want to click on a user that is not visible on the screen. for that i need to scroll down or swipe down but i am not able to do.
What i need to do to find a solution?????.

**Comment by garthenweb** [comment]
@anandb5  @dimplechauhan21 @AvinashPratap I finally found time to have a look into this. You can use the `flick` function to swipe up or down. I added an example with commit c416029bd2a2ccfef4707ade7e06ea1d1cb7ba7d.

See the [docs](http://appium.io/docs/en/commands/interactions/touch/flick/) and [code](https://github.com/admc/wd/blob/234a2155d95d51447c06683e5fa0684c9d2e8730/lib/commands.js#L1529) for more information to the flick function.
