### ISSUE TITLE
node_modules/vargs/lib/vargs.js: arguments is a reserved word in strict mode (24:37

### ISSUE THREAD

**Issue by adamhaney** [garthenweb/react-native-e2etest#4]
Thank you for putting this together. I was able to get it working based when directly cloning it but when I started trying to integrate it into my project I see the following error

```
 FAIL  __tests__/basic.e2e.js
  ● Test suite failed to run

/Repos/spoon/node_modules/vargs/lib/vargs.js: arguments is a reserved word in strict mode (24:37)
        22 | //   }
        23 | //
      > 24 | exports.Constructor = function Vargs(arguments) {
           |                                      ^
        25 |     this.array = Array.prototype.slice.call(arguments);
        26 |     this.__defineGetter__('length', function () {
        27 |         if (this.callbackGiven()) {
```

I know it's tangential to the project but I thought I'd ask if anything jumps out at you? It looks like vargs is an 8 year old dependency of the `wd` package, did you run into anything like this? I have a feeling it might have something to do with my babel settings.

**Comment by garthenweb** [comment]
@adamhaney I don't have issues like that so far. Your babel settings could of cause be the root of the issue. Did you touch the `.babelrc`? Maybe you like to share a repository or any guidance on how to reproduce your issue?

**Comment by garthenweb** [comment]
I close this issue because of inactivity. In case you have more information on this topic feel free to comment!
