### ISSUE TITLE
How to disable the send notification pop up

### ISSUE THREAD

**Issue by LayMuiToh** [garthenweb/react-native-e2etest#5]
I am following this tutorial to create a e2e test automation for my mobile app
However, every time I launch the iOS simulator, it will have a send notification popup

How do I get rid of this notification in my test code? I used device.launchApp with notifications YES does not work at all.

my code snippet:describe('Login Test', () => {

beforeAll(async () => {

try {

await driver.init(config, {launchApp: false});

await driver.sleep(2000); 

await device.launchApp({permissions: {

notifications: 'YES'}});

 

 

} catch(err)

{

console.log(err);

}

});

**Comment by LayMuiToh** [comment]
Hi, any help. I am still stuck with this send notification popup, how can I use the driver to set permission of the notification.
this code below does n't seem to work at all. the send notification popup is still there.

beforeEach(async () => {
      await driver.launchApp({permissions: {
        notifications: 'YES'}});
      });

**Comment by LayMuiToh** [comment]
this is resolved by adding "autoAcceptAlerts": "true" to the desired Capability at package.json "e2e": {
    "devices": {
      "ios-emulator": {
        "platformName": "iOS",
        "platformVersion": "10.3",
        "deviceName": "iPad (5th generation)",
        "autoAcceptAlerts": "true", 
        "app": "ios/build/Build/Products/Debug-iphonesimulator/AttachmentPro.app"
      }
    }
  },

**Comment by garthenweb** [comment]
As far as I understand this is resolved. In case it's not, feel free to comment!
PS: If you could provide an example to help others that struggle with this, I would highly appreciate a PR :)
